name: Package and Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get tag
              id: release_tag
              run: echo ::set-output name=TAG::"${GITHUB_REF/refs\/tags\//ttocontactshadow_}.zip"

            - name: checkout repo
              uses: actions/checkout@master

            - name: Update version number
              id: ver_update
              run: bash .github/workflows/setver.sh ${GITHUB_REF/refs\/tags\//}

            - name: Move contents to subdir
              id: move_files
              run: mkdir .tmpwork && mv * .tmpwork && mv .tmpwork ttocontactshadow

            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  filename: ${{ steps.release_tag.outputs.TAG }}
                  exclusions: "*.git* /*img/*"

            - name: Upload Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: ${{ steps.release_tag.outputs.TAG }}
                  token: ${{ secrets.GITHUB_TOKEN }}
